"""Run the retained full-data matrix through the production neural adapter.

Only the diagnostic case inventory changes in an isolated static tree. The
production runtime, arithmetic installer and original application bodies are
unchanged. Native matrix fixtures are never regenerated by this runner.
"""
import base64
import hashlib
import json
import os
import shutil
import subprocess
import time
import urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
from common import ROOT, PROOF, sha, write_json


def inputs():
    paths=[Path(__file__),PROOF/'requirements-native.lock',
           PROOF/'evidence/neural-training-matrix-probe.py',
           PROOF/'evidence/neural-training-matrix-native.npz',
           PROOF/'evidence/neural-training-matrix-inputs.json']
    paths += [p for p in (PROOF/'site').rglob('*') if p.is_file()]
    hashes={str(p.relative_to(PROOF)):sha(p) for p in sorted(paths)}
    return hashlib.sha256(json.dumps(hashes,sort_keys=True).encode()).hexdigest()


def main():
    site=PROOF/'cache/deployed-neural-matrix-site'
    if site.exists():shutil.rmtree(site)
    site.mkdir()
    for name in ('shinylive','assets','probes'):
        shutil.copytree(PROOF/'site'/name,site/name,copy_function=os.link)
    for name,source in [('unit5_probe.py','neural-training-matrix-probe.py'),
                        ('unit5-full-native.npz','neural-training-matrix-native.npz')]:
        target=site/'probes'/name
        target.unlink()  # Never write through a hardlink to retained inputs.
        shutil.copy2(PROOF/'evidence'/source,target)
    worker=(PROOF/'site/probes/unit5-worker.js').read_text()
    worker=worker.replace("json.dumps({'comparisons':",
        "np.savez_compressed('matrix-browser.npz',**arrays)\njson.dumps({'comparisons':")
    worker=worker.replace('    self.postMessage({done:true,',
        "    self.postMessage({artifact:py.FS.readFile('matrix-browser.npz')});\n    self.postMessage({done:true,")
    (site/'probes/matrix-worker.js').write_text(worker)
    from stage_image_workers import write_probe_config
    config=site/'probes/course-probe-image-loading.json'
    config.unlink(missing_ok=True)
    write_probe_config(site/'probes',worker='matrix-worker.js')
    beginning=inputs()
    server=subprocess.Popen(['node',str(ROOT/'tools/preview.mjs'),str(site)],
                            env=dict(os.environ,PORT='8031'),stdout=subprocess.DEVNULL)
    try:
        url='http://127.0.0.1:8031/probes/'
        for _ in range(100):
            try:urllib.request.urlopen(url,timeout=1).close();break
            except OSError:time.sleep(.1)
        with sync_playwright() as p:
            browser=p.chromium.launch(channel='chrome')
            try:
                page=browser.new_page();page.goto(url)
                outcome=page.evaluate('''()=>new Promise((resolve,reject)=>{
 const worker=new Worker('matrix-worker.js');let artifact;
 worker.onerror=e=>{worker.terminate();reject(new Error(e.message))};
 worker.onmessage=async e=>{
  if(e.data.artifact)artifact=new Promise(done=>{const reader=new FileReader();reader.onload=()=>done(reader.result.split(',')[1]);reader.readAsDataURL(new Blob([e.data.artifact]))});
  else if(e.data.error){worker.terminate();reject(new Error(e.data.error))}
  else if(e.data.done){worker.terminate();resolve({report:e.data,artifact:await artifact})}
 };worker.postMessage('unit5full');
})''')
                artifact=PROOF/'evidence/deployed-neural-matrix.npz'
                artifact.write_bytes(base64.b64decode(outcome['artifact']))
                result=outcome['report']
                passed=all(v['status']=='pass' for v in result['comparisons'].values())
                result.update(status='pass' if passed else 'fail',browser='chrome',distribution='installed',
                    version=browser.version,input_fingerprint=beginning,artifact_sha256=sha(artifact),
                    scope='Production adapter; retained complete original 3-epoch MNIST/Fashion-MNIST matrix: seeds 0/42/123, incomplete batches, flip/inversion.')
                if beginning!=inputs():result['observed_status']=result['status'];result['status']='stale'
                write_json(PROOF/'evidence/deployed-neural-matrix.json',result)
                print(result['status'],len(result['comparisons']),flush=True)
                return int(result['status']!='pass')
            finally:browser.close()
    finally:server.terminate();server.wait(timeout=10)


if __name__=='__main__':raise SystemExit(main())
